### ISSUE TITLE
Error handling when plugin added already exists

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ChRIS_ultron_backEnd#10]
We might want to handle gracefully the case when we try to add a plugin that has already been added to the system:

```
(chris-ultron) ubuntu@chris-ultron:~/chris-ultron-backend/chris_backend/plugins/services$ python manager.py --add simpledsapp
(chris-ultron) ubuntu@chris-ultron:~/chris-ultron-backend/chris_backend/plugins/services$ python manager.py --add simpledsapp
Traceback (most recent call last):
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/connections.py", line 270, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'simpledsapp' for key 'plugins_plugin_name_2e574762_uniq'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manager.py", line 186, in <module>
    manager.run()
  File "manager.py", line 65, in run
    self.add_plugin(options.name)
  File "manager.py", line 87, in add_plugin
    plugin.save()
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/MySQLdb/connections.py", line 270, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'simpledsapp' for key 'plugins_plugin_name_2e574762_uniq'")
```

**Comment by jbernal0019** [comment]
add_plugin method now rises an exception when there is an attempt to add an already existing plugin to the system
