### ISSUE TITLE
Can not POST to FEED on HTTPS

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ChRIS_ultron_backEnd#13]
On latest `#master`, doing a simple POST to create a new feed doesn't work:
`POST /api/v1/plugins/3 (with appropriate payload)`

returns:

```
Error:
[Mon Oct 24 06:11:21.831152 2016] [wsgi:error] [pid 9694:tid 139932718855936] [remote 10.0.2.2:49519] [Errno 2] No such file or directory: '/home/ubuntu/tmp/debug-charm.log'
```

Creating this directory manually bypasses the error but then get the following error:

```
[Mon Oct 24 06:18:56.341476 2016] [wsgi:error] [pid 10194:tid 140208603395840] [remote 10.0.2.2:50299]     if len(sys.argv) == 1: sys.exit(1)
[Mon Oct 24 06:18:56.341527 2016] [wsgi:error] [pid 10194:tid 140208603395840] [remote 10.0.2.2:50299] SystemExit: 1
```

https://github.com/FNNDSC/pman/blob/master/purl.py#L117

Commenting the line out, I get the following error:

```
[Mon Oct 24 06:21:06.444133 2016] [wsgi:error] [pid 10336:tid 140208688183040] [remote 10.0.2.2:50540] \x1b[1;33m---->
[Mon Oct 24 06:21:06.444159 2016] [wsgi:error] [pid 10336:tid 140208688183040] [remote 10.0.2.2:50540] 2016-10-24 06:21:06.444144 | http://10.0.2.15:5010/
[Mon Oct 24 06:21:06.444167 2016] [wsgi:error] [pid 10336:tid 140208688183040] [remote 10.0.2.2:50540]  {'meta': {'echoBack': 'Hi there!', 'askAbout': 'sysinfo'}, 'action': 'hello'}
[Mon Oct 24 06:21:06.444173 2016] [wsgi:error] [pid 10336:tid 140208688183040] [remote 10.0.2.2:50540] 
[Mon Oct 24 06:21:06.444181 2016] [wsgi:error] [pid 10336:tid 140208688183040] [remote 10.0.2.2:50540] \x1b[1;33m---->
[Mon Oct 24 06:21:06.444847 2016] [wsgi:error] [pid 10336:tid 140208688183040] [remote 10.0.2.2:50540] \x1b[0m\x1b[0;35m2016-10-24 06:21:06.444830 | Sending data...
[Mon Oct 24 06:21:06.445172 2016] [wsgi:error] [pid 10336:tid 140208688183040] [remote 10.0.2.2:50540] \x1b[0m(7, 'Failed to connect to 10.0.2.15 port 5010: Connection refused')
```

Looking into this one now, not sure if it could be HTTPS related issue or I am just missing a `pman` server running (I thought in latest version there was no need to start `pman` manually)

cc @rudolphpienaar

**Comment by NicolasRannou** [comment]
It only happens with the HTTPS server.

**Comment by NicolasRannou** [comment]
OK @rudolphpienaar @jbernal0019 running diagnostic on fresh vagrant VM:

**Comment by NicolasRannou** [comment]
* Running tests: 🔴 
* POST to pman: 🔴 
* POST to internal: 🔴 
* HTTPS POST to pman: 🔴  
* HTTPS POST to pman: 🔴

**Comment by NicolasRannou** [comment]
Running tests:

command:
```
python manage.py test
```

output:
```
...
            			| Welcome to purl.py |
            			+--------------------+
            

            This program sends REST conforming communication to a remote service over http.

            See 'purl.py --man commands' for more help.

            
                        Will transmit to                   http://10.0.2.15:5010
---->
2016-10-26 03:28:32.496860  | http://10.0.2.15:5010/
 {'action': 'run', 'meta': {'cmd': 'python3 /home/ubuntu/chris-ultron-backend/chris_backend/plugins/services/simplefsapp/simplefsapp.py /home/ubuntu/users/test/foo/feed_83/simplefsapp_85/data --saveopts /home/ubuntu/users/test/foo/feed_83/simplefsapp_85/opts.json --dir ./', 'threaded': True, 'auid': 'foo', 'jid': '85'}}
---->
2016-10-26 03:28:32.497102  | Sending data...
2016-10-26 03:28:32.613482  | response from call = {"meta": {"cmd": "python3 /home/ubuntu/chris-ultron-backend/chris_backend/plugins/services/simplefsapp/simplefsapp.py /home/ubuntu/users/test/foo/feed_83/simplefsapp_85/data --saveopts /home/ubuntu/users/test/foo/feed_83/simplefsapp_85/opts.json --dir ./", "auid": "foo", "threaded": true, "jid": "85"}, "path": "", "payloadsize": 333, "RESTverb": "POST", "receivedByServer": ["POST / HTTP/1.1\r", "Host: 10.0.2.15:5010\r", "User-Agent: PycURL/7.43.0 libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3\r", "Accept: */*\r", "Content-type: application/vnd.collection+json\r", "Content-Length: 333\r", "\r", "{\"payload\": {\"action\": \"run\", \"meta\": {\"cmd\": \"python3 /home/ubuntu/chris-ultron-backend/chris_backend/plugins/services/simplefsapp/simplefsapp.py /home/ubuntu/users/test/foo/feed_83/simplefsapp_85/data --saveopts /home/ubuntu/users/test/foo/feed_83/simplefsapp_85/opts.json --dir ./\", \"threaded\": true, \"auid\": \"foo\", \"jid\": \"85\"}}}"], "action": "run", "jobRootDir": "20161026032832.505478_aeed8d11-ba74-4de7-a21c-fa0cd6d2b809", "status": true, "RESTheader": "POST / HTTP/1.1\r"}
<----
2016-10-26 03:28:32.613943  | {"action": "run", "status": true, "jobRootDir": "20161026032832.505478_aeed8d11-ba74-4de7-a21c-fa0cd6d2b809", "payloadsize": 333, "RESTverb": "POST", "path": "", "receivedByServer": ["POST / HTTP/1.1\r", "Host: 10.0.2.15:5010\r", "User-Agent: PycURL/7.43.0 libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3\r", "Accept: */*\r", "Content-type: application/vnd.collection+json\r", "Content-Length: 333\r", "\r", "{\"payload\": {\"action\": \"run\", \"meta\": {\"cmd\": \"python3 /home/ubuntu/chris-ultron-backend/chris_backend/plugins/services/simplefsapp/simplefsapp.py /home/ubuntu/users/test/foo/feed_83/simplefsapp_85/data --saveopts /home/ubuntu/users/test/foo/feed_83/simplefsapp_85/opts.json --dir ./\", \"threaded\": true, \"auid\": \"foo\", \"jid\": \"85\"}}}"], "meta": {"threaded": true, "cmd": "python3 /home/ubuntu/chris-ultron-backend/chris_backend/plugins/services/simplefsapp/simplefsapp.py /home/ubuntu/users/test/foo/feed_83/simplefsapp_85/data --saveopts /home/ubuntu/users/test/foo/feed_83/simplefsapp_85/opts.json --dir ./", "auid": "foo", "jid": "85"}, "RESTheader": "POST / HTTP/1.1\r"}
<----

class
.........
======================================================================
FAIL: test_plugin_instance_detail_success (plugins.tests.test_views.PluginInstanceDetailViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/chris-ultron-backend/chris_backend/plugins/tests/test_views.py", line 200, in test_plugin_instance_detail_success
    self.assertContains(response, "pacspull")
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/test/testcases.py", line 374, in assertContains
    response, text, status_code, msg_prefix, html)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/site-packages/django/test/testcases.py", line 346, in _assert_contains
    " (expected %d)" % (response.status_code, status_code)
AssertionError: 500 != 200 : Couldn't retrieve content: Response code was 500 (expected 200)

----------------------------------------------------------------------
Ran 122 tests in 12.533s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

note: console hanging, doesn't return.

**Comment by NicolasRannou** [comment]
POST to pman:

command:
```
terminal 1 - start pman
$> python pman.py --raw 1 --http  --port 5011 --listeners 12

terminal 2 - start django server
(after updating charm properly: PORT and ARGS)
$> python manage.py runserver 0.0.0.0:8000

(optional) terminal 3 - add FS plugin is not already added
$> python manager.py --add simplefsapp
```

**Comment by NicolasRannou** [comment]
POST to pman HTTPS:

command:
```
terminal 2 - start https server:
$> python manage.py runmodwsgi --host 0.0.0.0 --port 8001 --https-port 8000 --ssl-certificate-file ../utils/ssl_cert/local.crt --ssl-certificate-key-file ../utils/ssl_cert/local.key --processes 8 --server-name localhost --https-only --reload-on-changes
```

results:
```
GET plugins:
$> http -a chris:Chris1234 GET https://localhost:8001/api/v1/plugins/ Content-Type:application/vnd.collection+json Accept:application/vnd.collection+json --verify=../utils/ssl_cert/local.crt
HTTP/1.1 200 OK
Allow: GET, HEAD, OPTIONS
Connection: close
Content-Type: application/vnd.collection+json
Date: Wed, 26 Oct 2016 08:01:29 GMT
Server: Apache
Transfer-Encoding: chunked
Vary: Accept
X-Frame-Options: SAMEORIGIN

{
    "collection": {
        "href": "https://localhost:8001/api/v1/plugins/", 
        "items": [
            {
                "data": [
                    {
                        "name": "name", 
                        "value": "simplefsapp"
                    }, 
                    {
                        "name": "type", 
                        "value": "fs"
                    }
                ], 
                "href": "https://localhost:8001/api/v1/plugins/1/", 
                "links": [
                    {
                        "href": "https://localhost:8001/api/v1/plugins/1/parameters/", 
                        "rel": "parameters"
                    }, 
                    {
                        "href": "https://localhost:8001/api/v1/plugins/1/instances/", 
                        "rel": "instances"
                    }
                ]
            }
        ], 
        "links": [
            {
                "href": "https://localhost:8001/api/v1/", 
                "rel": "feeds"
            }
        ], 
        "version": "1.0"
    }
}

```

**Comment by NicolasRannou** [comment]
POST to pman HTTPS:

setup:
```
replace 'pman' by 'internal' in manager.py (line 173)
```

results
```
POST to feed instance:
$>http -a chris:Chris1234 POST https://localhost:8001/api/v1/plugins/1/instances/ Content-Type:application/vnd.collection+json Accept:application/vnd.collection+json template:='{"data":[{"name":"dir","value":"./"}, {"name":"previous","value":""}]}' --verify=../utils/ssl_cert/local.crt
HTTP/1.1 201 Created
Allow: GET, POST, HEAD, OPTIONS
Connection: close
Content-Type: application/vnd.collection+json
Date: Wed, 26 Oct 2016 08:10:32 GMT
Location: https://localhost:8001/api/v1/plugins/instances/7/
Server: Apache
Transfer-Encoding: chunked
Vary: Accept
X-Frame-Options: SAMEORIGIN

{
    "collection": {
        "href": "https://localhost:8001/api/v1/plugins/1/instances/", 
        "items": [
            {
                "data": [
                    {
                        "name": "id", 
                        "value": 7
                    }, 
                    {
                        "name": "plugin_name", 
                        "value": "simplefsapp"
                    }, 
                    {
                        "name": "start_date", 
                        "value": "2016-10-26T08:10:32.415903Z"
                    }, 
                    {
                        "name": "end_date", 
                        "value": "2016-10-26T08:10:32.415963Z"
                    }, 
                    {
                        "name": "status", 
                        "value": "started"
                    }, 
                    {
                        "name": "owner", 
                        "value": "chris"
                    }
                ], 
                "href": "https://localhost:8001/api/v1/plugins/instances/7/", 
                "links": [
                    {
                        "href": "https://localhost:8001/api/v1/7/", 
                        "rel": "feed"
                    }, 
                    {
                        "href": "https://localhost:8001/api/v1/plugins/1/", 
                        "rel": "plugin"
                    }, 
                    {
                        "href": "https://localhost:8001/api/v1/plugins/string-parameter/7/", 
                        "rel": "string_param"
                    }
                ]
            }
        ], 
        "links": [], 
        "version": "1.0"
    }
}
```

```
Get instance of started plugin:
$>  http -a chris:Chris1234 GET https://localhost:8001/api/v1/plugins/instances/8/ Content-Type:application/vnd.collection+json Accept:application/vnd.collection+json --verify=../utils/ssl_cert/local.crt
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 531
Content-Type: text/html; charset=iso-8859-1
Date: Wed, 26 Oct 2016 08:14:57 GMT
Server: Apache

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

**Comment by NicolasRannou** [comment]
POST to internal:

setup:
```
replace 'pman' by 'internal' in manager.py (line 173)
```

results:
```
POST Feed instance
http -a chris:Chris1234 POST http://127.0.0.1:8001/api/v1/plugins/1/instances/ Content-Type:application/vnd.collection+json Accept:application/vnd.collection+json template:='{"data":[{"name":"dir","value":"./"}, {"name":"previous","value":""}]}'
HTTP/1.0 201 Created
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/vnd.collection+json
Date: Wed, 26 Oct 2016 08:22:12 GMT
Location: http://127.0.0.1:8001/api/v1/plugins/instances/10/
Server: WSGIServer/0.2 CPython/3.5.2
Vary: Accept
X-Frame-Options: SAMEORIGIN

{
    "collection": {
        "href": "http://127.0.0.1:8001/api/v1/plugins/1/instances/", 
        "items": [
            {
                "data": [
                    {
                        "name": "id", 
                        "value": 10
                    }, 
                    {
                        "name": "plugin_name", 
                        "value": "simplefsapp"
                    }, 
                    {
                        "name": "start_date", 
                        "value": "2016-10-26T08:22:11.790320Z"
                    }, 
                    {
                        "name": "end_date", 
                        "value": "2016-10-26T08:22:11.790391Z"
                    }, 
                    {
                        "name": "status", 
                        "value": "started"
                    }, 
                    {
                        "name": "owner", 
                        "value": "chris"
                    }
                ], 
                "href": "http://127.0.0.1:8001/api/v1/plugins/instances/10/", 
                "links": [
                    {
                        "href": "http://127.0.0.1:8001/api/v1/10/", 
                        "rel": "feed"
                    }, 
                    {
                        "href": "http://127.0.0.1:8001/api/v1/plugins/1/", 
                        "rel": "plugin"
                    }, 
                    {
                        "href": "http://127.0.0.1:8001/api/v1/plugins/string-parameter/10/", 
                        "rel": "string_param"
                    }
                ]
            }
        ], 
        "links": [], 
        "version": "1.0"
    }
}
```

```
Get feed instance:
http -a chris:Chris1234 GET http://127.0.0.1:8001/api/v1/plugins/instances/11/ Content-Type:application/vnd.collection+json Accept:application/vnd.collection+json
HTTP/1.0 500 Internal Server Error
Content-Type: application/vnd.collection+json
Date: Wed, 26 Oct 2016 08:23:06 GMT
Server: WSGIServer/0.2 CPython/3.5.2
X-Frame-Options: SAMEORIGIN

{
    "collection": {
        "error": {
            "message": "Internal server error"
        }, 
        "href": "http://127.0.0.1:8001/api/v1/plugins/instances/11/", 
        "version": "1.0"
    }
}
```

```
pman server
2016-10-26 08:23:57.265774 |     <Listener(Thread-11, started 140107126400768)> |                            run | Listener ID - 10: run() - Received comms from client.
2016-10-26 08:23:57.266198 |     <Listener(Thread-11, started 140107126400768)> |                            run | Listener ID - 10: run() - Ready to serve...
2016-10-26 08:23:57.267028 |     <Listener(Thread-12, started 140107118008064)> |                            run | Listener ID - 11: run() - Received comms from client.
2016-10-26 08:23:57.267482 |     <Listener(Thread-12, started 140107118008064)> |                        process | Listener ID - 11: process() - handling request
2016-10-26 08:23:57.267969 |     <Listener(Thread-12, started 140107118008064)> |                        process | 
2016-10-26 08:23:57.268590 |     <Listener(Thread-12, started 140107118008064)> |                        process | ***********************************************
2016-10-26 08:23:57.269040 |     <Listener(Thread-12, started 140107118008064)> |                        process | ***********************************************
2016-10-26 08:23:57.269582 |     <Listener(Thread-12, started 140107118008064)> |                        process | 2016-10-26 08:23:57.267935 incoming data stream
2016-10-26 08:23:57.270113 |     <Listener(Thread-12, started 140107118008064)> |                        process | ***********************************************
2016-10-26 08:23:57.270692 |     <Listener(Thread-12, started 140107118008064)> |                        process | len = 285
2016-10-26 08:23:57.271245 |     <Listener(Thread-12, started 140107118008064)> |                        process | ***********************************************
2016-10-26 08:23:57.271775 |     <Listener(Thread-12, started 140107118008064)> |                        process | POST / HTTP/1.1
Host: 10.0.2.15:5011
User-Agent: PycURL/7.43.0 libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3
Accept: */*
Content-type: application/vnd.collection+json
Content-Length: 72

{"payload": {"action": "status", "meta": {"key": "jid", "value": "11"}}}

2016-10-26 08:23:57.272383 |     <Listener(Thread-12, started 140107118008064)> |                        process | ***********************************************
2016-10-26 08:23:57.272952 |     <Listener(Thread-12, started 140107118008064)> |                        process | Request = ...
2016-10-26 08:23:57.273498 |     <Listener(Thread-12, started 140107118008064)> |                        process | ['POST / HTTP/1.1\r', 'Host: 10.0.2.15:5011\r', 'User-Agent: PycURL/7.43.0 libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3\r', 'Accept: */*\r', 'Content-type: application/vnd.collection+json\r', 'Content-Length: 72\r', '\r', '{"payload": {"action": "status", "meta": {"key": "jid", "value": "11"}}}']
2016-10-26 08:23:57.274047 |     <Listener(Thread-12, started 140107118008064)> |                    processPOST | Will process request in current thread.
2016-10-26 08:23:57.274652 |     <Listener(Thread-12, started 140107118008064)> |               t_status_process | In status process...
2016-10-26 08:23:57.276097 |     <Listener(Thread-12, started 140107118008064)> |                      job_state | In done process...
2016-10-26 08:23:57.277264 |     <Listener(Thread-12, started 140107118008064)> |               t_search_process | In search process...
2016-10-26 08:23:57.278701 |     <Listener(Thread-12, started 140107118008064)> |               t_search_process | {'value': '11', 'key': 'jid'}
2016-10-26 08:23:57.280197 |     <Listener(Thread-12, started 140107118008064)> |               t_search_process | False
2016-10-26 08:23:57.286532 |     <Listener(Thread-12, started 140107118008064)> |                            run | Listener ID - 11: run() - Sending response to client.
2016-10-26 08:23:57.286803 |     <Listener(Thread-12, started 140107118008064)> |                            run | JSON formatted response:
2016-10-26 08:23:57.287355 |     <Listener(Thread-12, started 140107118008064)> |                            run | {"path": "", "d_ret": {"l_status": [], "-1": {"noJobFound": {"endInfo": {"allJobsDone": null}}}}, "payloadsize": 72, "status": false, "action": "status", "RESTverb": "POST", "receivedByServer": ["POST / HTTP/1.1\r", "Host: 10.0.2.15:5011\r", "User-Agent: PycURL/7.43.0 libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3\r", "Accept: */*\r", "Content-type: application/vnd.collection+json\r", "Content-Length: 72\r", "\r", "{\"payload\": {\"action\": \"status\", \"meta\": {\"key\": \"jid\", \"value\": \"11\"}}}"], "meta": {"value": "11", "key": "jid"}, "RESTheader": "POST / HTTP/1.1\r"}
2016-10-26 08:23:57.288004 |     <Listener(Thread-12, started 140107118008064)> |                            run | len = 602 chars
2016-10-26 08:23:57.288855 |     <Listener(Thread-12, started 140107118008064)> |                            run | Listener ID - 11: run() - Ready to serve...
2016-10-26 08:23:57.290052 |     <Listener(Thread-13, started 140107109615360)> |                            run | Listener ID - 12: run() - Received comms from client.
2016-10-26 08:23:57.291256 |     <Listener(Thread-13, started 140107109615360)> |                            run | Listener ID - 12: run() - Ready to serve...
```

```
Django server:

            			+---------------------+
            			| Welcome to Charm.py |
            			+---------------------+
            

            Charm is the interface class/code between ChRIS and a pman process management
            system.

            See 'charm.py --man commands' for more help.

            
2016-10-26 04:23:57.261338  | d_args         = {}
2016-10-26 04:23:57.261830  | app_args       = {}
2016-10-26 04:23:57.262330  | d_pluginInst   = {   '_state': <django.db.models.base.ModelState object at 0x7f44a56c3550>,
    'end_date': datetime.datetime(2016, 10, 26, 8, 22, 52, 972006, tzinfo=<UTC>),
    'id': 11,
    'owner_id': 1,
    'plugin_id': 1,
    'previous_id': None,
    'start_date': datetime.datetime(2016, 10, 26, 8, 22, 52, 971964, tzinfo=<UTC>),
    'status': 'started'}
2016-10-26 04:23:57.262419  | d_pluginRepr   = {}
2016-10-26 04:23:57.263093  | app            = None
2016-10-26 04:23:57.263142  | inputdir       = 
2016-10-26 04:23:57.263162  | outputdir      = 


            			+--------------------+
            			| Welcome to purl.py |
            			+--------------------+
            

            This program sends REST conforming communication to a remote service over http.

            See 'purl.py --man commands' for more help.

            
                        Will transmit to                   http://10.0.2.15:5011
---->
2016-10-26 04:23:57.264589  | http://10.0.2.15:5011/
 {'action': 'status', 'meta': {'key': 'jid', 'value': '11'}}
---->
2016-10-26 04:23:57.265257  | Sending data...
2016-10-26 04:23:57.289039  | response from call = {"path": "", "d_ret": {"l_status": [], "-1": {"noJobFound": {"endInfo": {"allJobsDone": null}}}}, "payloadsize": 72, "status": false, "action": "status", "RESTverb": "POST", "receivedByServer": ["POST / HTTP/1.1\r", "Host: 10.0.2.15:5011\r", "User-Agent: PycURL/7.43.0 libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3\r", "Accept: */*\r", "Content-type: application/vnd.collection+json\r", "Content-Length: 72\r", "\r", "{\"payload\": {\"action\": \"status\", \"meta\": {\"key\": \"jid\", \"value\": \"11\"}}}"], "meta": {"value": "11", "key": "jid"}, "RESTheader": "POST / HTTP/1.1\r"}
<----
2016-10-26 04:23:57.289291  | {"action": "status", "receivedByServer": ["POST / HTTP/1.1\r", "Host: 10.0.2.15:5011\r", "User-Agent: PycURL/7.43.0 libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3\r", "Accept: */*\r", "Content-type: application/vnd.collection+json\r", "Content-Length: 72\r", "\r", "{\"payload\": {\"action\": \"status\", \"meta\": {\"key\": \"jid\", \"value\": \"11\"}}}"], "path": "", "meta": {"key": "jid", "value": "11"}, "status": false, "payloadsize": 72, "d_ret": {"-1": {"noJobFound": {"endInfo": {"allJobsDone": null}}}, "l_status": []}, "RESTverb": "POST", "RESTheader": "POST / HTTP/1.1\r"}
<----

list index out of range
[26/Oct/2016 04:23:57] "GET /api/v1/plugins/instances/11/ HTTP/1.1" 500 136
```
