### ISSUE TITLE
Tests cannot run in parallel

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ultron_backEnd#289]
```
$ docker-compose -f docker-compose_dev.yml exec chris_dev python manage.py test --parallel
Creating test database for alias 'default'...
Cloning test database for alias 'default'...
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/test.py", line 53, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python3.8/dist-packages/django/test/runner.py", line 629, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/test/runner.py", line 552, in setup_databases
    return _setup_databases(
  File "/usr/local/lib/python3.8/dist-packages/django/test/utils.py", line 178, in setup_databases
    connection.creation.clone_test_db(
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/creation.py", line 216, in clone_test_db
    self._clone_test_db(suffix, verbosity, keepdb)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/creation.py", line 55, in _clone_test_db
    self._clone_db(source_database_name, target_database_name)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/creation.py", line 64, in _clone_db
    with subprocess.Popen(dump_cmd, stdout=subprocess.PIPE) as dump_proc:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mysqldump'

$ docker-compose -f docker-compose_dev.yml exec -u root chris_dev apt-get install -y mysql-client

$ docker-compose -f docker-compose_dev.yml exec chris_dev python manage.py test --parallel  
Creating test database for alias 'default'...
Got an error creating the test database: (1007, "Can't create database 'test_chris_dev'; database exists")
Type 'yes' if you would like to try deleting the test database 'test_chris_dev', or 'no' to cancel: yes
Destroying old test database for alias 'default'...
Cloning test database for alias 'default'...
Destroying old test database for alias 'default'...
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'test_chris_dev' AND TABLE_NAME = 'auth_group';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
```

**Comment by jennydaman** [comment]
Closing because unimportant.
