### ISSUE TITLE
Error when running plugins test

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/ChRIS_ultron_backEnd#8]
Does it look familiar @jbernal0019 ?

```
(chris-ultron) ubuntu@chris-ultron:~/chris-ultron-backend/chris_backend$ python manage.py test
Creating test database for alias 'default'...
....................................................................................................EEEE......
======================================================================
ERROR: test_plugin_instance_create_failure_unauthenticated (plugins.tests.test_views.PluginInstanceListViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/chris-ultron-backend/chris_backend/plugins/services/manager.py", line 45, in _get_plugin_app_class
    plugin_app_module = import_module(plugin_app_module_name)
  File "/home/ubuntu/python-envs/chris-ultron/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'plugins.services.simpleapp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/chris-ultron-backend/chris_backend/plugins/tests/test_views.py", line 146, in setUp
    pl_manager.add_plugin('simpleapp')
  File "/home/ubuntu/chris-ultron-backend/chris_backend/plugins/services/manager.py", line 74, in add_plugin
    plugin_app_class = self._get_plugin_app_class(name)
  File "/home/ubuntu/chris-ultron-backend/chris_backend/plugins/services/manager.py", line 48, in _get_plugin_app_class
    plugin's app package was added." % plugin_app_module_name)
ImportError: Error: failed to import module plugins.services.simpleapp.simpleapp. Check if the                  plugin's app package was added.

**Comment by jbernal0019** [comment]
Basically the problem is that there is no simpleapp plugin app in the system anymore.
I replaced it by two new apps simplefsapp and simpledsapp. So it would be enough to change the name of the app in those tests simpleapp-->simplefsapp
